use crate::config::PymgrConfig;
use crate::errors::{ErrorCode, PymgrError, PymgrResult};
use crate::lockfile::Lockfile;

pub fn exec(format: Option<&str>, hashes: bool) -> PymgrResult<()> {
    let project_dir = PymgrConfig::find_project_root()?;
    let path = project_dir.join("pymgr.lock");

    if !path.exists() {
        return Err(PymgrError::coded(
            ErrorCode::LockfileMissing,
            "pymgr.lock not found. Run `pymgr add` or `pymgr install` first.",
        ));
    }

    let lockfile = Lockfile::load(&path)?;
    let fmt = format.unwrap_or("requirements");

    if fmt == "requirements" {
        println!("# Generated by pymgr — do not edit manually");
        if hashes {
            println!("# pymgr export requirements --hashes\n");
        } else {
            println!("# pymgr export requirements\n");
        }

        for pkg in &lockfile.packages {
            if hashes && !pkg.sha256.is_empty() {
                println!("{}=={} \\", pkg.name, pkg.version);
                println!("    --hash=sha256:{}", pkg.sha256);
            } else {
                println!("{}=={}", pkg.name, pkg.version);
            }
        }
    } else if fmt == "conda" {
        println!("# Generated by pymgr");
        println!("name: project");
        println!("channels:");
        println!("  - defaults");
        println!("  - conda-forge");
        println!("dependencies:");
        println!("  - python={}", lockfile.metadata.python);
        println!("  - pip");
        println!("  - pip:");
        for pkg in &lockfile.packages {
            println!("    - {}=={}", pkg.name, pkg.version);
        }
    } else {
        return Err(PymgrError::coded(
            ErrorCode::ConfigError,
            format!("Unsupported export format: {}", fmt),
        ));
    }

    Ok(())
}
